### PR TITLE
Add Get Spatial Locations API

### PR DESCRIPTION
**Pull request by gnedster**
Not exactly a formal pull request per se, but I wanted to get your thoughts on having an API which extracts the location information from the intermediate sparse grids without having to construct a dense representation. I've built this for a very specific use case, so if you think this could be more general please let me know.

### CODE REVIEW

**Comment by btgraham** [comment]
Thanks for the diff. This is ok for batches of size 1. To accommodate larger batches, it would be natural to add an extra column with the batch information, matching the input format to 'setLocations'.

**Comment by gnedster** [comment]
Yes, it's not clear which points they belong to but I've made a bit of shortcut on my end which works for batch sizes > 1 but I'd agree that it's not an appropriate API. 

I also agree we should be consistent, but I'm also thinking (from our previous discussion) we could just use a second tensor with start/end indices to indicate the ownership of the point information allowing for an even sparser representation rather than creating a new column. I could make the requisite changes on the setLocations as well. Let me know what you think.

**Comment by btgraham** [comment]
For consistency, I am returning the SpatialLocations as an nPoints x (Dimension + 1)  LongTensor.
The coordinates are then
> returnValue.narrow(1,0,dimension)
and the batch indices are
> returnValue[:,dimension]
As you have noticed, at the moment it is the case that returnValue[:,dimension] is a (non-strictly) increasing sequence. However, I would prefer not to guarantee that just in case it rules out some future optimization!

**Comment by gnedster** [comment]
Great! Thanks for the quick turnaround.

**Pull request merged**
